import { Red_Hat_Text } from 'next/font/google'
import './global.css'

const red_hat = Red_Hat_Text({ subsets: ['latin'] })
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={red_hat.className}>{children}</body>
    </html>
  )
}
